on:
  push:
    branches:
      - "release/*"

jobs:
  Lock_development_branch:
    runs-on: ubuntu-latest
    name: A job to lock the develop branch
    steps:
      - name: Checkout
        uses: Fdhansen/BranchProtectionTest@v1.6
      - name: Lock branch step
        uses: ./
        id: lock_branch
        with:
          auth-token: ${{ secrets.AUTHTOKEN }}
      - name: Get the output time
        run: echo "The time was ${{ steps.lock_branch.outputs.time }}"
